name = "Cobblemon"
author = "Jim Simon"
version = "1.31.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "459f5cf493580657558d513c7afcafe9438ad47d8cde36572d94433d25ac9fcd"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
