name = "Cobblemon"
author = "Jim Simon"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e77ee0efeb8a442f55f80b7e04225c25b70bc6265df5a075b693681c73ccee09"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
